apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ngroks.ngrok.com
spec:
  group: ngrok.com
  names:
    kind: Ngrok
    listKind: NgrokList
    plural: ngroks
    singular: ngrok
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Ngrok status
      jsonPath: .status.status
      name: Status
      type: string
    - description: Ngrok URL
      jsonPath: .status.url
      name: URL
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Ngrok is the Schema for the ngroks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NgrokSpec defines the desired state of Ngrok
            properties:
              auth:
                type: string
              authtoken:
                type: string
              hostname:
                type: string
              inspect:
                default: false
                type: boolean
              port:
                format: int32
                type: integer
              protocol:
                default: http
                enum:
                - http
                - tcp
                type: string
              region:
                enum:
                - us
                - eu
                - ap
                - au
                - sa
                - jp
                - in
                type: string
              remote_addr:
                type: string
              service:
                type: string
            required:
            - port
            - service
            type: object
          status:
            description: NgrokStatus defines the observed state of Ngrok
            properties:
              status:
                type: string
              url:
                type: string
            required:
            - status
            - url
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
